name: Release

on:
  push:
    paths:
      - "netbox_topology_icons/**"
      - "pyproject.toml"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install PDM
        run: pip3 install pdm

      - name: "Update PATH"
        run: echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: "Declare variables"
        id: vars
        run: |
          echo "::set-output name=version::$(pdm show --version)"
          echo "::set-output name=commit::$GITHUB_SHA"

      - name: "Build project for distribution"
        run: pdm build

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "dist/*"
          token: ${{ secrets.GITHUB_TOKEN }}
          name: "Icons v${{ steps.vars.outputs.version }}"
          tag: "v${{ steps.vars.outputs.version }}"
          allowUpdates: true
          draft: false
